/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMessageBo: typeof import('element-plus/es')['ElMessageBo']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
